### ISSUE TITLE
Migrating #discord-bots pins to the site

### ISSUE THREAD

**Issue by Shom770** [discord-python/site#695]
This issue is for the ongoing project to migrate all the pinned messages in #discord-bots to the website under the [guides](https://www.pythondiscord.com/pages/guides/python-guides/).

# Pins to be Migrated
If any of the pins below are checked off (checkmark next to the pin), a pull request has already been opened for that pin, and the pull request will be linked.

- [x] [Messages with Colors](https://discord.com/channels/267624335836053506/343944376055103488/928909158764396554) (Krypton) (#691)
- [x] [Discord Embed Limits](https://discord.com/channels/267624335836053506/343944376055103488/849552077092552704) (Krypton) (#690)
- [x] [Custom Help Commands](https://discord.com/channels/267624335836053506/343944376055103488/874712618827403375) (Raven) (#698)
- [x] [VPS services](https://discord.com/channels/267624335836053506/343944376055103488/874667287918026802) (Python) (#697)
- [x] [Replit vs Heroku](https://discord.com/channels/267624335836053506/343944376055103488/869084309334663169) (Raven) this is to be added to the above VPS page
- [x] [Discord bot token information](https://discord.com/channels/267624335836053506/343944376055103488/845290598394494997) (Tizzy) (#701)
- [x] [Why JSON is unsuitable as a database](https://discord.com/channels/267624335836053506/343944376055103488/822824159091884042) (Xithrius) (#700)
- [x] [Fixing SSL Certificate Issue](https://discord.com/channels/267624335836053506/343944376055103488/716675308253610074) (Stella) (#796)
- [x] [Setting different statuses on your bot](https://discord.com/channels/267624335836053506/343944376055103488/730574118658900039) (iamericfletcher) (#709)
- [x] [on_command_error eating unhandled errors](https://discord.com/channels/267624335836053506/343944376055103488/796212280244305970) (Atom) (#765)

# Additional Topics
The following topics below are additional topics that can be added to the site, regarding discord bots.
- [x] Tutorial on subclassing Bot (#702) (Waiting for author)
- [x] Tutorial on subclassing Context (#703) (Needs review)
- [x] DevOps guide for Discord Bots (#746) (Waiting for author)
- [x] Hikari guide (#738) (Closed due to lack of review)
- [x] Application Commands Guide (#733) (Waiting for author)

# Tags
Per request, we also want to scope the addition of new tags as part of this project.
These tags should follow the same traditional pattern as any other tag that we would add.
They should mostly cover common "pitfalls" or "gotchas" or any other very common topic that would benefit from a tag, as everything else (like a getting started guide)
is covered both in discord.py's documentation and our own site resources. Below are a few to start off with:
- [x] Message content intent (https://github.com/python-discord/bot/pull/2566)
- [x] Bot not responding to commands (briefly mention the above message content tag, but primarily explain `@bot.event` and `on_message`) (https://github.com/python-discord/bot/pull/2567)
- [x] Short tag linking to #discord-bot-hosting (https://github.com/python-discord/bot/pull/2472)

If anybody has any more ideas, please feel free to leave them in the comments below.
If you'd like to work on any of then, mention @Robin5605 with which one you want to take on.

# Helping with the migration of pin(s)
If anyone wants to help migrate a pin, you would want to create a markdown file here within `pydis_site/apps/content/resources/guides/python-guides`, with a structure along the lines of:
```md
---
title: Guide Title
description: Guide Description
---
# Pin content goes here
```

Please read this guide on [how to contribute a page](https://www.pythondiscord.com/pages/guides/pydis-guides/how-to-contribute-a-page/).

**Comment by sue-m-oh** [comment]
Hi @Robin5605 

Can you please look into combining these duplicate files? They share duplicate content. 

- https://www.pythondiscord.com/pages/guides/python-guides/vps-services/
- https://www.pythondiscord.com/pages/guides/python-guides/vps_services/

**Comment by Robin5605** [comment]
#799

**Comment by Robin5605** [comment]
Hello! So the main goal of the project is complete. All the pins  linked here have been migrated to site. The only ones left are the "additional topics" (#702 and #703).
Can we consider this project to be complete, or do we want to include the additional topics section as part of the project as well? 
Thanks!

**Comment by Robin5605** [comment]
Updated original comment with the new "Tags" section which has been scoped as part of this project

**Comment by n0Oo0Oo0b** [comment]
Can I make a page on using cogs/extensions?

**Comment by jchristgit** [comment]
> Can we consider this project to be complete, or do we want to include the additional topics section as part of the project as well?

Let's keep it open until we have those two PRs merged. I think we should have that done soon 🙂

**Comment by jchristgit** [comment]
> Can I make a page on using cogs/extensions?

@n0Oo0Oo0b Personally I'm not opposed to it but I believe it would be better to discuss in a new issue, as this one is mainly related to migrating existing content. Could you open one?

**Comment by Xithrius** [comment]
Two previously mentioned PRs have been merged, along with everything else listed in the main comment of this issue.
